### ISSUE TITLE
RayGuy 3.0

### ISSUE THREAD

**Issue by funlw65** [GuvaCode/Ray4Laz#12]
Any chance to have the header? We compile the C library ourselves. Thank you!

**Comment by GuvaCode** [comment]
Header in pascal?

**Comment by GuvaCode** [comment]
> Any chance to have the header? We compile the C library ourselves. Thank you!

Header in pascal?

**Comment by GuvaCode** [comment]
Yes it can be done. But I can't compile raylib with rlgui in Linux. If you give me a solution, I will do it.

**Comment by funlw65** [comment]
RayGui cpde was separated from RayLib, continues to depend on RayLib but if someone wants, can be made to use only GLFW library if certain functions are provided.
  
raygui.h must be renamed to raygui,c then compiled with a specific option to create a standalone library (be it statically or dynamically, it is specified here https://github.com/raysan5/raygui). This must be made by the user. Only then a ray_gui.pas (by header, as is named in C and FreeBasic, I meant unit) can be used.  For now, I reverted to your previous version, as is used by both FreePascal and FreeBasic...

**Comment by GuvaCode** [comment]
> RayGui cpde was separated from RayLib, continues to depend on RayLib but if someone wants, can be made to use only GLFW library if certain functions are provided.
> 
> raygui.h must be renamed to raygui,c then compiled with a specific option to create a standalone library (be it statically or dynamically, it is specified here https://github.com/raysan5/raygui). This must be made by the user. Only then a ray_gui.pas (by header, as is named in C and FreeBasic, I meant unit) can be used. For now, I reverted to your previous version, as is used by both FreePascal and FreeBasic...

Yes, thank you, I've already figured it out. 
The new version is already in the works.
It'll be ready in an hour or two.

**Comment by funlw65** [comment]
Thank you, man! You are awesome!

**Comment by GuvaCode** [comment]
implemented !!!

**Comment by funlw65** [comment]
Thank you very much, Gunko!
