### ISSUE TITLE
BindPose/FramePoses Rotation not working

### ISSUE THREAD

**Issue by realmworksxyz** [GuvaCode/Ray4Laz#13]
Anyone else experiencing this issue on Windows? Any leads on what might be the culprit?

**Comment by realmworksxyz** [comment]
One workaround I found would be to use Translation instead of Rotation and Vector3RotateByQuaternion.

**Comment by realmworksxyz** [comment]
Looks to be a raylib issue and UpdateMeshBuffer seems to be the way to go for deforming a mesh.

**Comment by GuvaCode** [comment]
> Looks to be a raylib issue and UpdateMeshBuffer seems to be the way to go for deforming a mesh.

FModel.transform:=MatrixRotateXYZ(Vector3Create(DEG2RAD*FAxisX,DEG2RAD*FAxisY,DEG2RAD*FAxisZ))

**Comment by realmworksxyz** [comment]
I should have specified that I want to rotate the bones associated with specific vertices of a mesh and there seems to be an issue where a mesh does not transform with the skinning when bones are manipulated.

**Comment by GuvaCode** [comment]
Okay. Then we should check with the author of raylib
