### ISSUE TITLE
How to publish as apk

### ISSUE THREAD

**Issue by toutiewa** [GuvaCode/Ray4Laz#15]
How to publish as apk

**Comment by GuvaCode** [comment]
It will be quite difficult. I never tried to collect for android. 
but you can try it yourself. 
https://github.com/raysan5/raylib/wiki/Working-for-Android
Well, of course, with **corrections** for Pascal.

 `have to change mingw32-make PLATFORM=PLATFORM_ANDROID to mingw32-make PLATFORM=PLATFORM_ANDROID RAYLIB_LIBTYPE=SHARED 
`
and possibly many more 

while I had no plans to try to collect for android. Well, **if I have time, I'll try.**
