### ISSUE TITLE
Delphi support

### ISSUE THREAD

**Issue by turborium** [GuvaCode/Ray4Laz#18]
Is it possible to add Delphi support in header files?
I looked code and i think, this solved by a small number of IFDEF'S.

**Comment by GuvaCode** [comment]
Привет. Я не планирую поддерживать делфи. Так как у меня нету даже машин с виндой. 
Я сам на работе компилирую под винду чтобы проверить биндинг.

**Comment by GuvaCode** [comment]
Ну вы сами можете форкнуть и добавить поддержку Делфи. 
 Ps. Здоровье вам и вашим близким. 
Pass. Надеюсь что скоро увижу новый ролик от вам. А то уже почти год тишина на канале.

**Comment by zaher** [comment]
I have my own header for that, it is FPC and Delphi compiled
https://github.com/parmaja/tyro/tree/master/src/raylib
