### ISSUE TITLE
raylib window context to OpenGLControl (initial code)

### ISSUE THREAD

**Issue by ghost** [GuvaCode/Ray4Laz#19]
- Requirements:
   - [GLFW for Free Pascal/Lazarus](https://github.com/Blueicaro/GLFW)  
   - [DLL etc.](https://www.glfw.org/download)
- Docs:
  - https://github.com/raysan5/raylib/issues/1216

Still working on this, but the rendering happens in the TOpenGLControl on the form.

```
uses
OpenGLContext, raylib, glfw, Windows;
```

```
  TPortFrm = class(TForm)
    OpenGLControl1: TOpenGLControl;
    procedure FormCreate(Sender: TObject);
    procedure OpenGLControl1Paint(Sender: TObject);
  private
    WndContext: pGLFWwindow;
  public

  end;
```

```
procedure TPortFrm.FormCreate(Sender: TObject);
begin
  InitWindow(1600, 900, 'port');
  SetTargetFPS(60);
  WndContext:=glfwGetCurrentContext();
  OpenGLControl1.Handle:=HWND(WndContext);
end; 
```
```
procedure TPortFrm.OpenGLControl1Paint(Sender: TObject);
begin
  while not WindowShouldClose do begin
    BeginDrawing;
    ClearBackground(RED);
    OpenGLControl1.SwapBuffers;
    EndDrawing;
  end;
end; 
```

**Comment by GuvaCode** [comment]
wow. It's very interesting I'll do it today.

**Comment by runtimeninja** [comment]
> wow. It's very interesting I'll do it today.

thanks, appreciate it!

**Comment by GuvaCode** [comment]
well. I tried without gltf. I got the handle by means of raylib itself. but under gtk2 it all crashes. there is an idea to wrap it all in streams.

**Comment by runtimeninja** [comment]
> well. I tried without glfw. I got the handle by means of raylib itself. but under gtk2 it all crashes. there is an idea to wrap it all in streams.

i can test your implemenations on Windows, whenever you're ready

**Comment by runtimeninja** [comment]
my previous OnPaint event led to freezing, so by removing the while loop, it allowed me to keep the form from freezing

```
procedure TPortFrm.OpenGLControl1Paint(Sender: TObject);
begin
    BeginDrawing;
    ClearBackground(RED);
    EndDrawing;
    OpenGLControl1.SwapBuffers;
end;  
```

**Comment by runtimeninja** [comment]
DrawFPS seems to be causing a crash, testing 3D stuff next w/wo rlgl standalone methods

**Comment by GuvaCode** [comment]
Well, I don't understand what's going wrong. when swapbuffer crashes. gtk2 and qt5

**Comment by GuvaCode** [comment]
I was only able to call a separate window through a thread. But I've done this before https://github.com/GuvaCode/Ray4LazExample/tree/main/Visual_3d_Camera_in_LCL

**Comment by runtimeninja** [comment]
> I was only able to call a separate window through a thread. But I've done this before https://github.com/GuvaCode/Ray4LazExample/tree/main/Visual_3d_Camera_in_LCL

thanks, maybe your code will do the trick for me, since this looks like a black box.
my wild guess is that the opengl state gets mixed up somewhere along the line

**Comment by GuvaCode** [comment]
and why do you need output on the lcl context?
now I'm writing a binding for another engine.https://worldsim3d.forumotion.com/t7-worldsim3d-development-roadmap
you can join

**Comment by runtimeninja** [comment]
> and why do you need output on the lcl context? now I'm writing a binding for another engine.https://worldsim3d.forumotion.com/t7-worldsim3d-development-roadmap you can join

mostly for the convienience of it and to see how it would work
for now, i can check out the engine every now and again

**Comment by GuvaCode** [comment]
can I learn your native language?

**Comment by GuvaCode** [comment]
Финский ? Или латыш?

**Comment by runtimeninja** [comment]
well, its finnish (see profile)
so we're neighbouring countries :P
unfortunately i can't speak russian

**Comment by GuvaCode** [comment]
"unfortunately i can't speak russian " bad. I was really hoping

**Comment by runtimeninja** [comment]
so, i would like to be able to have window events from lcl for a viewport picker that relies on lcl
is this possible outside of forms?

**Comment by runtimeninja** [comment]
> unfortunately

😂
