### ISSUE TITLE
Basic lighting example is black

### ISSUE THREAD

**Issue by ghost** [GuvaCode/Ray4Laz#20]
Box and plane are black in shaders_basic_lighting. How do I fix them? I use Windows.

**Comment by GuvaCode** [comment]
Try the example from the master branch.
there is also a problem if you use intel graphics

**Comment by tribality** [comment]
> Try the example from the master branch. there is also a problem if you use intel graphics

Yes, main branch downloaded and command line tells me it renders with NVIDIA card.

**Comment by GuvaCode** [comment]
well, I don't have the opportunity to check under windows right now. under linux, everything works correctly for me

**Comment by tribality** [comment]
> well, I don't have the opportunity to check under windows right now. under linux, everything works correctly for me

Ok but thank you

**Comment by tribality** [comment]
C version runs well, so I will look for a bug in here.

**Comment by GuvaCode** [comment]
Да. Скорее всего ошибка в коде. Я не обновлял давно примеры

**Comment by tribality** [comment]
> Yes. Most likely an error in the code. I haven't updated the examples in a while

I see

**Comment by GuvaCode** [comment]
Are you using a dynamic library? I have the same problem only if I use static linking
