### ISSUE TITLE
Move examples to a separate repo

### ISSUE THREAD

**Issue by glowiak** [GuvaCode/Ray4Laz#25]
When there are loads of examples (especially huge ones) in the repo, it significantly slows down the process of git-cloning it.

Would be good to move them to a separate repository and add a mention in the README about it.

**Comment by GuvaCode** [comment]
For large repositories it is possible. For example Castle Game Engine is about 1 gigabyte.
I don't think it's worth moving the examples to a separate repository for < 50 megabytes.
