### ISSUE TITLE
Some examples don't work for me

### ISSUE THREAD

**Issue by vertikalm** [GuvaCode/Ray4Laz#27]
I'm testing Ray4Laz, on Linux (Debian12), with Lazarus 3.0 fixed. Most examples work correctly.

* The 2 GUI-based examples do not work correctly. The 'controls-test-suite' does not show 3 'edit-boxes'. Of the rest of the controls that are displayed, none of those in the second column work. But the build is successful.

* Most examples about 'shaders' are not displayed either, although the compilation is successful.

Should I compile with some special modifier? I have tested with different processors and graphics cards with the same results.

**Comment by GuvaCode** [comment]
Examples with controls need to be rewritten. I know this problem, but there is no time yet.

Try to run the compiled shader examples separately, not from the environment.

And please write the ones that don't work for you. And if possible, the log is not a working example

**Comment by vertikalm** [comment]
> Try to run the compiled shader examples separately, not from the environment.

Indeed, the shader examples run correctly from the command line. The rgui controls do not, at least on Linux.

**Comment by GuvaCode** [comment]
I rewrote the control test suite example

**Comment by vertikalm** [comment]
Works like a charm :)
