### ISSUE TITLE
release 5.5 not installed  and problem in the extraction phase.

### ISSUE THREAD

**Issue by axel18bsm** [GuvaCode/Ray4Laz#34]
Hi,
I can't install the new realese after the remove of the old one (5.0).
After the download of the file,  at the beginning  of the extraction I have this error.
![image](https://github.com/user-attachments/assets/2832eda1-c601-4d90-914b-3758e6e64742)

I' m at windows 11, lazarus 3.6 and i have no d:/ xxxxx. The error msg in English is :  it s not possible to extract ::
Thank you for your help.

**Comment by axel18bsm** [comment]
perhaps the 2 points in the name ([ray4laz_simpleprj..uk.po](https://github.com/GuvaCode/ray4laz/blob/main/package/lang/**ray4laz_simpleprj..uk.po**)

**Comment by GuvaCode** [comment]
@axel18bsm Thank you. the problem has been solved and updated

**Comment by axel18bsm** [comment]
I have tried, it s ok now. Thank you for your help.
