### ISSUE TITLE
Getting specific 5.5 raylib release instead of master

### ISSUE THREAD

**Issue by harryvederci** [GuvaCode/ray4laz#36]
The `builds_raylib.sh` script currently downloads the latest master branch code.

I guess it would be more stable (/accurate to the description of the ray4laz repo) to get the specific 5.5 release:
https://github.com/raysan5/raylib/archive/refs/tags/5.5.zip

But maybe there's a reason to get the master branch instead?

**Comment by GuvaCode** [comment]
I probably need to rewrite it with a choice of release or trunk. in theory, this script is used to quickly assemble the trunk.
