### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Ifelsethendo** [GuvaCode/Ray4Laz#5]
Installed through package manager. Load examples.
 If there is not some error like:
models_animation.pas(31,40) Error: Call by var for arg no. 1 has to match exactly: Got "Pointer" expected "TMaterial"
ray_header.pas(1270,11) Hint: Found declaration: SetMaterialTexture(var TMaterial;LongInt;TTexture); CDecl;

Then the example compiles, runs, exits without anything ever showing up on screen.

Same with the program template from the file> new menu.

**Comment by GuvaCode** [comment]
Вы не могли бы  какая у вас система?  Windows или Linux?
Кака версия raylib установлена?

**Comment by GuvaCode** [comment]
Yes, there is a problem with Windows. Namely with the DrawModelEx function.

**Comment by Ifelsethendo** [comment]
Ah, okay, thanks for response. Have fun!
