### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by BearHeathen** [GuvaCode/Ray4Laz#6]
Windows 10 x64
Lazarus 2.2.0RC2 (built via fpcupdeluxe)
OPM: Installed Ray4Laz

Receiving "**raylib.dll not found...**" error. Rebuilding ray4laz_designtime v.4.0 removes this error. However, I still get the "**Execution stopped with exit-code 1073741515**" error. See screenshots for specific error messages.

_Admittedly, this may be completely user error. Nonetheless, your work is invaluable and in the event someone else might get this fringe error it may be worth documenting._

![ray1](https://user-images.githubusercontent.com/7244519/141478927-fea74ce0-8d41-42b1-9aa9-03b89478468b.png)
![ray2](https://user-images.githubusercontent.com/7244519/141478937-798d9f94-e01e-4a77-9e02-c97595e4ea76.png)

**Comment by GuvaCode** [comment]
Which version of raylib did you put in mingw or gcc?
I would recommend trying gcc. https://github.com/raysan5/raylib/releases/download/4.0.0/raylib-4.0.0_win64_msvc16.zip

**Comment by BearHeathen** [comment]
Just wanted to post for future reference: 

Adding these references did indeed cause the app to function as intended!

![image](https://user-images.githubusercontent.com/7244519/141882117-2e324705-5ec4-4ae2-9984-b5e3c2fb9c55.png)
